### ISSUE TITLE
Tricouri și diplome Summer Workshops

### ISSUE THREAD

**Issue by maria** [rosedu/meta#9]
## TODOs
- Elaborare design pentru diplome, cu logo-ul Summer Workshops - am folosit http://canva.com: 
  - [x] Quantum Computation & Cryptography
  - [x] The Science of Photography. A Journey from Photon to JPEG (due date: 22 sept)
  - [x] The (Black) Magic of Pixels. An Image Processing Primer. (due date: 18 sept)
  - [x] Data Science with Python, Scala and Apache Spark (?)
  - [x] Design Patterns (due date: 6 sept)  
- Diplomele trebuie facute in format electronic pentru toti participantii, asadar le trebuie semnatura si stampila:   
  - [x] Quantum Computation & Cryptography
  - [x] The Science of Photography. A Journey from Photon to JPEG (due date: 23 sept)
  - [x] The (Black) Magic of Pixels. An Image Processing Primer.(due date: 19 sept)
  - [x] Data Science with Python, Scala and Apache Spark (?)
  - [x] Design Patterns (due date: 7 sept)
- [ ] ~~Logo format vectorial sau png pentru logo-ul Summer Workshops.~~ - Nu am găsit, TODO pentru viitor.
- [ ] ~~Comanda print pentru tricouri - logo-ul SW pe spate / fata si cel al ROSEdu pe fata / maneca.~~ Vom oferi doar diplome.
## Notes
- Lista de participanti pentru care oferim diplome o primim de la organizatori / Flori
- De asemenea, trebuie sa facem in hub.rosedu.org sectiune pentru diplome. -> issue in hub.

**Comment by vilie** [comment]
Se caută template de diplome sau de comandat/printat?

**Comment by maria** [comment]
Pentru diplome nu avem template, nu am căutat in Drive. Pentru Tricouri nu avem un logo - cel al evenimentului pentru design. Trebuie printate/comandate apoi.

**Comment by mariuscoto** [comment]
GG!
